name: gitartwork from a contribution graph

on: 
  push:
  schedule:
    - cron: '0 0 * * *'  # This will run the job daily at midnight UTC

jobs:
  build:
    name: Make gitartwork SVG
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: .github/actions/gitartwork

      - name: Generate gitartwork SVG
        run: node generate-gitartwork.js
        working-directory: .github/actions/gitartwork
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USER_NAME: jasineri
          TEXT: ARPAN

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Update gitartwork SVG'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          
